"""Anonymize personal names in text files using spaCy NER and HIPS (Hiding in Plain Sight).

Detects PER (person name) entities with a trained spaCy model and replaces
them with realistic fake names generated by Faker, preserving document
readability while removing identifying information.
"""

import logging
import os
import random
from pathlib import Path

import pandas as pd
import spacy
from faker import Faker
from natsort import natsorted

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Bundled data helpers
# ---------------------------------------------------------------------------

def _data_dir() -> str:
    """Return the path to the bundled data directory."""
    return os.path.join(os.path.dirname(__file__), "data")


def default_ner_model_path() -> str:
    """Return the path to the bundled spaCy NER model (cv0, PER entity)."""
    return os.path.join(_data_dir(), "ner_model")


# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------

def generate_fake_names(n: int = 50, seed: int | None = None) -> list[str]:
    """Generate a pool of *n* unique fake full names.

    Parameters
    ----------
    n : int
        Number of fake names to generate.
    seed : int or None
        Random seed for reproducibility.
    """
    fake = Faker()
    if seed is not None:
        Faker.seed(seed)
        random.seed(seed)

    names: set[str] = set()
    while len(names) < n:
        names.add(fake.name())
    return list(names)


def load_ner_model(model_dir: str | None = None) -> spacy.Language:
    """Load a trained spaCy NER model from *model_dir*.

    Falls back to the bundled model when *model_dir* is ``None``.
    """
    if model_dir is None:
        model_dir = default_ner_model_path()
    logger.info("Loading NER model from: %s", model_dir)
    return spacy.load(model_dir)


def _trim_entity(start: int, end: int, text: str) -> tuple[int, int, str]:
    """Trim whitespace and non-name tokens from entity span edges.

    The NER model occasionally produces spans that bleed into adjacent
    field labels or trailing whitespace (e.g. ``"John Smith\\nConsultant"``).
    This trims the span back to just the name portion.
    """
    # Strip trailing whitespace / newlines
    trimmed = text.rstrip()
    end = start + len(trimmed)

    # If the trimmed text still contains a newline, keep only the first line
    if "\n" in trimmed:
        trimmed = trimmed.split("\n")[0].rstrip()
        end = start + len(trimmed)

    # Strip leading whitespace / newlines
    original_len = len(trimmed)
    trimmed = trimmed.lstrip()
    start += original_len - len(trimmed)

    return start, end, trimmed


def extract_per_entities(nlp: spacy.Language, text: str) -> list[tuple[int, int, str]]:
    """Return ``(start_char, end_char, text)`` for every PER entity in *text*."""
    doc = nlp(text)
    entities = []
    for ent in doc.ents:
        if ent.label_ == "PER":
            start, end, name = _trim_entity(ent.start_char, ent.end_char, ent.text)
            if name:  # skip if trimming left nothing
                entities.append((start, end, name))
    return entities


def anonymize_text(
    text: str,
    entities: list[tuple[int, int, str]],
    fake_names: list[str],
) -> tuple[str, int, dict[str, str]]:
    """Replace PER entities with fake names (HIPS).

    Uses consistent mapping: the same original name always maps to the same
    fake name within a single call.  Entities are replaced in reverse order
    to preserve character offsets.

    Returns
    -------
    tuple[str, int, dict]
        (anonymized_text, replacement_count, name_mapping)
    """
    if not entities:
        return text, 0, {}

    name_mapping: dict[str, str] = {}
    sorted_entities = sorted(entities, key=lambda x: x[0], reverse=True)

    anonymized = text
    count = 0
    for start, end, original in sorted_entities:
        if original not in name_mapping:
            name_mapping[original] = random.choice(fake_names)
        anonymized = anonymized[:start] + name_mapping[original] + anonymized[end:]
        count += 1

    return anonymized, count, name_mapping


def anonymize_single(
    input_file: str,
    output_file: str,
    nlp: spacy.Language,
    fake_names: list[str],
) -> dict:
    """Anonymize a single ``.txt`` file.

    Parameters
    ----------
    input_file : str
        Path to the source text file.
    output_file : str
        Path where the anonymized file will be written.
    nlp : spacy.Language
        Loaded spaCy NER model.
    fake_names : list[str]
        Pool of fake names to draw from.

    Returns
    -------
    dict
        ``{"file", "replacements", "names_found", "name_mapping"}``
    """
    text = Path(input_file).read_text(encoding="utf-8")
    entities = extract_per_entities(nlp, text)
    original_names = [e[2] for e in entities]

    anonymized_text, count, name_mapping = anonymize_text(text, entities, fake_names)

    out = Path(output_file)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(anonymized_text, encoding="utf-8")

    logger.info(
        "Anonymized %s — %d name(s) replaced %s",
        Path(input_file).name,
        count,
        original_names if original_names else "",
    )
    return {
        "file": str(input_file),
        "replacements": count,
        "names_found": original_names,
        "name_mapping": name_mapping,
    }


def anonymize_batch(
    input_dir: str,
    output_dir: str,
    model_dir: str | None = None,
    n_fake_names: int = 50,
    seed: int | None = None,
) -> pd.DataFrame:
    """Anonymize all ``.txt`` files in *input_dir* and write results to *output_dir*.

    Parameters
    ----------
    input_dir : str
        Directory containing ``.txt`` files.
    output_dir : str
        Destination directory (created if it doesn't exist).
    model_dir : str or None
        Path to a spaCy NER model directory.  Uses the bundled model when ``None``.
    n_fake_names : int
        Size of the fake-name pool.
    seed : int or None
        Random seed for reproducibility.

    Returns
    -------
    pd.DataFrame
        Log with columns: ``file``, ``replacements``, ``names_found``.
    """
    input_dir = os.path.abspath(input_dir)
    output_dir = os.path.abspath(output_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")

    os.makedirs(output_dir, exist_ok=True)

    nlp = load_ner_model(model_dir)
    fake_names = generate_fake_names(n=n_fake_names, seed=seed)
    logger.info("Generated pool of %d fake names", len(fake_names))

    txt_files = natsorted(Path(input_dir).glob("*.txt"))
    if not txt_files:
        logger.warning("No .txt files found in %s", input_dir)
        return pd.DataFrame(columns=["file", "replacements", "names_found"])

    logger.info("Found %d .txt file(s) to anonymize", len(txt_files))

    records: list[dict] = []
    for fpath in txt_files:
        out_path = os.path.join(output_dir, fpath.name)
        result = anonymize_single(str(fpath), out_path, nlp, fake_names)
        records.append({
            "file": result["file"],
            "replacements": result["replacements"],
            "names_found": result["names_found"],
        })

    log_df = pd.DataFrame(records)
    log_path = os.path.join(output_dir, "anonymization_log.csv")
    log_df.to_csv(log_path, index=False)
    logger.info("Anonymization log saved to %s", log_path)

    return log_df
